name: 'build'

on:
  schedule:
    - cron: "30 4 * * *"
  push:
    branches:
      - master

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        severity: error
  install-on-ubuntu-2404:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v1
    - name: script
      run: bash ${GITHUB_WORKSPACE}/install.sh
      shell: bash
  install-on-ubuntu-2604:
    runs-on: ubuntu-26.04
    steps:
    - uses: actions/checkout@v1
    - name: script
      run: bash ${GITHUB_WORKSPACE}/install.sh
      shell: bash
  install-on-macos-15:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v1
    - name: script
      run: bash ${GITHUB_WORKSPACE}/install.sh
      shell: bash
  install-on-macos-26:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v1
    - name: script
      run: bash ${GITHUB_WORKSPACE}/install.sh
      shell: bash
